const alur = [
  {
    title: 'Pengumpulan berkas',
    description: 'Kumpulkan berkas foto copy ijazah dan fotocopy KTP',
    progress: 100,
    path: 'submitberkas',
    color: '#9b5de5',
    locked: false,
  },
  {
    title: 'Pemilihan pembimbing',
    description: 'Kumpulkan berkas foto copy ijazah dan fotocopy KTP',
    progress: 50,
    path: 'pilihdosen',
    color: '#f15bb5',
    locked: false,
  },
  {
    title: 'Pengumpulan judul',
    description: 'Kumpulkan berkas foto copy ijazah dan fotocopy KTP',
    progress: 0,
    path: 'pilihdosen',
    color: '#52b600',
    locked: true,
  },
  {
    title: 'Bimbingan BAB 1',
    description: 'Kumpulkan berkas foto copy ijazah dan fotocopy KTP',
    progress: 0,
    path: 'pilihdosen',
    color: '#0582ca',
    locked: true,
  },
  {
    title: 'Bimbingan BAB 2',
    description: 'Kumpulkan berkas foto copy ijazah dan fotocopy KTP',
    progress: 0,
    path: 'pilihdosen',
    color: '#335c67',
    locked: true,
  },
  {
    title: 'Bimbingan BAB 3',
    description: 'Kumpulkan berkas foto copy ijazah dan fotocopy KTP',
    progress: 0,
    path: 'pilihdosen',
    color: 'border-green-500',
    locked: true,
  },
  {
    title: 'Bimbingan BAB 4',
    description: 'Kumpulkan berkas foto copy ijazah dan fotocopy KTP',
    progress: 0,
    path: 'pilihdosen',
    color: 'border-green-500',
    locked: true,
  },
  {
    title: 'Pemilihan penguji',
    description: 'Kumpulkan berkas foto copy ijazah dan fotocopy KTP',
    progress: 0,
    path: 'pilihdosen',
    color: 'border-green-500',
    locked: true,
  },
  {
    title: 'Ujian',
    description: 'Kumpulkan berkas foto copy ijazah dan fotocopy KTP',
    progress: 0,
    path: 'pilihdosen',
    color: 'border-green-500',
    locked: true,
  },
  {
    title: 'Revisi',
    description: 'Kumpulkan berkas foto copy ijazah dan fotocopy KTP',
    progress: 0,
    path: 'pilihdosen',
    color: 'border-green-500',
    locked: true,
  },
  {
    title: 'Pengumpulan skripsi',
    description: 'Kumpulkan berkas foto copy ijazah dan fotocopy KTP',
    progress: 0,
    path: 'pilihdosen',
    color: 'border-green-500',
    locked: true,
  },
]

export default alur